import React from "react";
import Head from "next/head";
import * as s from "./styles";

export default function CenteredDivLayout({ children }) {
  return (
    <div>
      <Head>
        <title>BuJo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <s.GlobalCSS/>
      <s.Wrapper>
        <h1>Welcome!</h1>
        <s.Container>{children}</s.Container>
      </s.Wrapper>
      
    </div>
  );
}
