import React from "react";
import Head from "next/head";
import * as s from "./styles";


export default function CenteredDivLayout({ children }) {
  return (
    <div>
      <Head>
        <title>iTask</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <s.GlobalCSS/>
      <s.Wrapper>
        <s.Container>{children}</s.Container>
        <s.ImageContainer></s.ImageContainer>
      </s.Wrapper>
    </div>
  );
}
