import React from 'react'
import Head from "next/head";
import * as s from './styles'



export const MainLayout = ({children}) => {
  return (
    <div>
      <Head>
        <title>iTask</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <s.GlobalCSS/>
      <s.Wrapper>
      {children}
      </s.Wrapper>
    </div>
  )
}
