import React, { useContext } from "react";
import Head from "next/head";
import { UserContext } from "../../../pages/_app";
import * as s from "./styles";
import { NavBar } from "../../organisms/navBar";

export const MainLayout = ({ state, children }) => {
  const { userData, setUserData } = useContext(UserContext);
  return (
    <div>
      <Head>
        <title>iTask</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <s.GlobalCSS />
      <s.Wrapper>
        <NavBar state={state} />
        <main>
          {userData ? <h1>Welcome {userData.username}!</h1> : <h1>Welcome!</h1>}
          {children}
        </main>
        <aside>SideSection</aside>
      </s.Wrapper>
    </div>
  );
};
